import { AccountCategoriesApi } from './api/';
import { AccountCategoryTypesApi } from './api/';
import { AccountLinksApi } from './api/';
import { AccountsApi } from './api/';
import { CustomersApi } from './api/';
import { FlexPlansApi } from './api/';
import { GenericResourcesApi } from './api/';
import { GenericResourceTeamMembersApi } from './api/';
import { GlobalConfigurationsApi } from './api/';
import { HolidaySchemesApi } from './api/';
import { PeriodsApi } from './api/';
import { PermissionRolesApi } from './api/';
import { PlanApprovalsApi } from './api/';
import { PlansApi } from './api/';
import { ProgramApi } from './api/';
import { RolesApi } from './api/';
import { SkillAssignmentsApi } from './api/';
import { SkillsApi } from './api/';
import { TeamApi } from './api/';
import { TeamLinksApi } from './api/';
import { TeamMembershipsApi } from './api/';
import { TimesheetApprovalsApi } from './api/';
import { UserScheduleApi } from './api/';
import { WorkAttributesApi } from './api/';
import { WorkloadSchemesApi } from './api/';
import { WorklogsApi } from './api/';
import { HttpBearerAuth } from './model/models';
export * from './api/';
export * from './model/models';
export interface TempoApiOptions {
    bearerToken: string;
}
export default class TempoApi {
    readonly config: TempoApiOptions;
    readonly auth: HttpBearerAuth;
    readonly accountCategories: AccountCategoriesApi;
    readonly accountCategoryTypes: AccountCategoryTypesApi;
    readonly accountLinks: AccountLinksApi;
    readonly accounts: AccountsApi;
    readonly customers: CustomersApi;
    readonly genericResources: GenericResourcesApi;
    readonly genericResourceTeamMembers: GenericResourceTeamMembersApi;
    readonly globalConfiguration: GlobalConfigurationsApi;
    readonly holidaySchemes: HolidaySchemesApi;
    readonly periods: PeriodsApi;
    readonly permissionRoles: PermissionRolesApi;
    readonly planApprovals: PlanApprovalsApi;
    readonly plans: PlansApi;
    readonly programs: ProgramApi;
    readonly roles: RolesApi;
    readonly skillAssignments: SkillAssignmentsApi;
    readonly skills: SkillsApi;
    readonly teams: TeamApi;
    readonly flexPlans: FlexPlansApi;
    readonly teamMemberships: TeamMembershipsApi;
    readonly teamLinks: TeamLinksApi;
    readonly timesheetApprovals: TimesheetApprovalsApi;
    readonly userSchedule: UserScheduleApi;
    readonly workAttributes: WorkAttributesApi;
    readonly workloadSchemes: WorkloadSchemesApi;
    readonly worklogs: WorklogsApi;
    constructor(options: TempoApiOptions);
}
//# sourceMappingURL=api.d.ts.map