"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
var api_1 = require("./api/");
var api_2 = require("./api/");
var api_3 = require("./api/");
var api_4 = require("./api/");
var api_5 = require("./api/");
var api_6 = require("./api/");
var api_7 = require("./api/");
var api_8 = require("./api/");
var api_9 = require("./api/");
var api_10 = require("./api/");
var api_11 = require("./api/");
var api_12 = require("./api/");
var api_13 = require("./api/");
var api_14 = require("./api/");
var api_15 = require("./api/");
var api_16 = require("./api/");
var api_17 = require("./api/");
var api_18 = require("./api/");
var api_19 = require("./api/");
var api_20 = require("./api/");
var api_21 = require("./api/");
var api_22 = require("./api/");
var api_23 = require("./api/");
var api_24 = require("./api/");
var api_25 = require("./api/");
var api_26 = require("./api/");
var models_1 = require("./model/models");
// This is the entrypoint for the package
__exportStar(require("./api/"), exports);
__exportStar(require("./model/models"), exports);
var TempoApi = /** @class */ (function () {
    function TempoApi(options) {
        this.accountCategories = new api_1.AccountCategoriesApi();
        this.accountCategoryTypes = new api_2.AccountCategoryTypesApi();
        this.accountLinks = new api_3.AccountLinksApi();
        this.accounts = new api_4.AccountsApi();
        this.customers = new api_5.CustomersApi();
        this.genericResources = new api_7.GenericResourcesApi();
        this.genericResourceTeamMembers = new api_8.GenericResourceTeamMembersApi();
        this.globalConfiguration = new api_9.GlobalConfigurationsApi();
        this.holidaySchemes = new api_10.HolidaySchemesApi();
        this.periods = new api_11.PeriodsApi();
        this.permissionRoles = new api_12.PermissionRolesApi();
        this.planApprovals = new api_13.PlanApprovalsApi();
        this.plans = new api_14.PlansApi();
        this.programs = new api_15.ProgramApi();
        this.roles = new api_16.RolesApi();
        this.skillAssignments = new api_17.SkillAssignmentsApi();
        this.skills = new api_18.SkillsApi();
        this.teams = new api_19.TeamApi();
        this.flexPlans = new api_6.FlexPlansApi();
        this.teamMemberships = new api_21.TeamMembershipsApi();
        this.teamLinks = new api_20.TeamLinksApi();
        this.timesheetApprovals = new api_22.TimesheetApprovalsApi();
        this.userSchedule = new api_23.UserScheduleApi();
        this.workAttributes = new api_24.WorkAttributesApi();
        this.workloadSchemes = new api_25.WorkloadSchemesApi();
        this.worklogs = new api_26.WorklogsApi();
        this.config = options;
        this.auth = new models_1.HttpBearerAuth();
        this.auth.accessToken = this.config.bearerToken;
        this.accountCategories.setDefaultAuthentication(this.auth);
        this.accountCategoryTypes.setDefaultAuthentication(this.auth);
        this.accountLinks.setDefaultAuthentication(this.auth);
        this.accounts.setDefaultAuthentication(this.auth);
        this.customers.setDefaultAuthentication(this.auth);
        this.genericResources.setDefaultAuthentication(this.auth);
        this.globalConfiguration.setDefaultAuthentication(this.auth);
        this.holidaySchemes.setDefaultAuthentication(this.auth);
        this.periods.setDefaultAuthentication(this.auth);
        this.permissionRoles.setDefaultAuthentication(this.auth);
        this.plans.setDefaultAuthentication(this.auth);
        this.programs.setDefaultAuthentication(this.auth);
        this.roles.setDefaultAuthentication(this.auth);
        this.teamMemberships.setDefaultAuthentication(this.auth);
        this.teamLinks.setDefaultAuthentication(this.auth);
        this.teams.setDefaultAuthentication(this.auth);
        this.timesheetApprovals.setDefaultAuthentication(this.auth);
        this.userSchedule.setDefaultAuthentication(this.auth);
        this.workAttributes.setDefaultAuthentication(this.auth);
        this.workloadSchemes.setDefaultAuthentication(this.auth);
        this.worklogs.setDefaultAuthentication(this.auth);
    }
    return TempoApi;
}());
exports.default = TempoApi;
module.exports = TempoApi;
